# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.0
    hooks:
    # -   id: style-files
    #     args: [--style_pkg=styler.mlr, --style_fun=mlr_style]
    # -   id: roxygenize
    #     # roxygen requires loading pkg -> add dependencies from DESCRIPTION
    #     additional_dependencies:
    #     -    bbotk
    #     -    checkmate
    #     -    cluster
    #     -    data.table
    #     -    distr6
    #     -    factoextra
    #     -    GGally
    #     -    ggfortify
    #     -    ggparty
    #     -    ggplot2
    #     -    glmnet
    #     -    knitr
    #     -    lgr
    #     -    mlr3
    #     -    mlr3cluster
    #     -    mlr3filters
    #     -    mlr3learners
    #     -    mlr3misc
    #     -    mlr3proba
    #     -    mlr3tuning
    #     -    paradox
    #     -    partykit
    #     -    patchwork
    #     -    precrec
    #     -    ranger
    #     -    rpart
    #     -    scales
    #     -    stats
    #     -    survival
    #     -    testthat
    #     -    utils
    #     -    vdiffr
    #     -    xgboost
    #     -    mlr-org/styler.mlr
    -   id: use-tidy-description
    # -   id: spell-check
        exclude: >
          (?x)^(
          data/.*|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData|
          .*\.svg
          )$
    # -   id: lintr
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: deps-in-desc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: end-of-file-fixer
        exclude: '\.Rd'
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
