# dev cmd check workflow of the mlr3 ecosystem v0.1.0
# https://github.com/mlr-org/actions
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: dev-check

jobs:
  check-package:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.dev-package }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release', dev-package: "mlr-org/paradox', 'mlr-org/mlr3learners', 'mlr-org/mlr3cluster', 'mlr-org/bbotk', 'mlr-org/mlr3tuning"}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install dev versions
        run: pak::pkg_install(c('${{ matrix.config.dev-package }}'))
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
